name: Setup project

on:
  workflow_call:
    inputs:
      node-version:
        default: '16'
        required: false
        type: string

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Install pnpm and dependencies
      uses: pnpm/action-setup@v2.1.0
      with:
        version: latest
        run_install: true
